CREATE TABLE "GCG_4580_CUT_SCREEN"(
 "LVL_P" CHAR(7),
 "LVL_C" CHAR(7),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "LENGTH" INTEGER,
 "WIDTH" INTEGER,
 "SERIAL" CHAR(20),
 "ALOC_TYPE" CHAR(1),
 "ALOC_VALUE" CHAR(20));