CREATE TABLE "GCG_4580_PO_LINEDIMS"(
 "PO" CHAR(6),
 "PO_LINE" CHAR(3),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "SLABS" INTEGER,
 "LENGTH" INTEGER,
 "WIDTH" INTEGER,
 "QUANTITY" DOUBLE,
 "TOTAL_QTY_LINE" DOUBLE);