CREATE TABLE "GCG_4580_PO_REQ_DIMS"(
 "PO_REQ" CHAR(6),
 "PO_REQ_LINE" CHAR(3),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "SLABS" INTEGER,
 "LENGTH" INTEGER,
 "WIDTH" INTEGER,
 "QUANTITY" CHAR(20),
 "TOTAL_QTY_LINE" DOUBLE);